### ISSUE TITLE
Can this CVE leak real /etc/passwd file instead of an error page?

### ISSUE THREAD

**Issue by Vccxx** [BrotherOfJhonny/grafana#2]

**Comment by doggopadre** [comment]
Not legit

**Comment by BrotherOfJhonny** [comment]
The failure is not a path traversal, but a session control failure. When the traversal path is explored, the authentication system redirects to an internal system page that should only be accessed by authenticated users.

**Comment by doggopadre** [comment]
> 

But then its just a Dashboard Template without any session context

**Comment by BrotherOfJhonny** [comment]
> Mas então é apenas um modelo de painel sem nenhum contexto de sessão

Exactly, it is directed to the internal page where it is possible to navigate through the system menus but without any active session.
Again remembering that this should be accessible only by authenticated users, so I consider it a low vulnerability.
